name: Deploy Streamlit App with Ollama

on:
  push: # Trigger the workflow on pushes to the main branch
    branches:
      - main
  schedule: # Trigger the workflow every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # Specify the Python version required by your app

      # Step 3: Install Python dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Install and Run Ollama
      - name: Install and Run Ollama
        run: |
          curl -sSL https://ollama.ai/install | bash
          ollama pull llama3.2-vision

      # Step 5: Execute Streamlit App
      - name: Run Streamlit App
        run: |
          streamlit run apps.py --server.headless true --server.port 8501

      # Step 6: Deploy to Streamlit Cloud (Optional Step)
      # Streamlit Cloud automatically deploys from the repository when changes are pushed.
      # If you'd prefer manual deployment, you can configure it directly at https://streamlit.io/cloud.
