name: Deploy Streamlit App with Ollama

on:
  push: # Trigger the workflow on pushes to the main branch
    branches:
      - main
  schedule: # Trigger the workflow every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the specified repository
      - name: Clone Repository
        run: |
          git clone https://github.com/svprasanth/analystvivek.git
          cd analystvivek

      # Step 2: Set up Python 3.13
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Step 3: Install Python dependencies
      - name: Install Dependencies
        run: |
          cd analystvivek
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Verify and Install Ollama
      - name: Install Ollama
        run: |
          curl -sSL https://ollama.ai/install -o ollama-install.sh
          chmod +x ollama-install.sh
          ./ollama-install.sh || echo "Failed to install Ollama. Check the installer URL or dependencies."

      # Step 5: Pull the Llama3.2-Vision model
      - name: Pull Llama Model
        run: |
          ollama pull llama3.2-vision || echo "Failed to pull model. Ensure Ollama is installed correctly."

      # Step 6: Execute the Streamlit App
      - name: Run Streamlit App
        run: |
          cd analystvivek
          streamlit run apps.py --server.headless true --server.port 8501
