name: Deploy Streamlit App on Streamlit Cloud

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13" # Use Python 3.9 as recommended by Streamlit Cloud

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run Streamlit App locally (optional step for debugging)
      - name: Run Streamlit App
        run: |
          streamlit run apps.py --server.headless true --server.port 8501
